apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-webapp-test-dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: student-webapp-test-dev
  template:
    metadata:
      labels:
        app: student-webapp-test-dev
    spec:
      containers:
      - name: student-webapp-test-dev
        image: harishtiru/student-webapp-test-dev:v25
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: student-webapp-test-dev
spec:
  selector:
    app: student-webapp-test-dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002 # Choose any available port number between 30000 and 32767
  type: NodePort
