---
apiVersion: v1
kind: Service
metadata:
  name: student-web-app
spec:
  selector:
    app: student-web-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000 # Choose any available port number between 30000 and 32767
  type: NodePort
